name: Local Deploy
on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: "0.129.0"

jobs:
  deploy:
    if: github.repository_owner == 'm-lyon'
    runs-on: ubuntu-latest
    environment:
      name: local-deploy
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: "repo"
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build
        env:
          HUGO_ENVIRONMENT: production
        run: |
          (cd repo; hugo --gc --minify -b "https://mattlyon.co.uk/")
      - name: Generate Pagefind search index
        run: npx pagefind --site repo/public
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr"
          SOURCE: repo/
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT}}
          TARGET: ${{ secrets.SSH_TARGET }}
